name: TSC

on:
  push:
    branches:
      - 3.x
  pull_request:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: yarn
        run: yarn install
      - name: config
        run: cp etc/config.example.json etc/config.json
      - name: tsc
        uses: icrawl/action-tsc@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          job-name: tsc
